### ISSUE TITLE
Current state of build process and testing integration.

### ISSUE THREAD

**Issue by KingScooty** [romainberger/yeoman-wordpress#11] opened 2013-01-17 14:07 UTC
Sweet generator! Two questions:

Does the build process update the header.php and footer.php files with the concatenated CSS and JS files during the build process? And does this generator currently work with RequireJS? I see `index.js` referencing version 2.0.5; as far as i'm aware, the current version of Rjs is 2.1.2, so i'm just curious on the current state of integration.

I'd be keen to utilise this on a project, but i'm not sure how the build system currently works. Also, are the JS tests setup to work out the box with Mocha/PhantomJS?

**Comment by romainberger** [comment] 2013-01-17 14:24
I am currently working on the build task so for now it's not working. I am working on it in the build branch if you want to take a look. 
It does not work with RequireJS for now either.

The JS tests are not included right now.

Sorry the generator is not complete yet, it takes time to adapt everything to the way Wordpress works.

**Comment by KingScooty** [comment] 2013-01-17 14:28
No problem! I'll try and sit down later and work on this, see if i can integrate it a bit more. 
Can you list what you've changed, what is working and what isn't, and what parts are using the default yeoman generator/build code?

**Comment by romainberger** [comment] 2013-01-17 14:43
I tried to comment the code clearly, but here is what the build task does for now:
- parse the php files to get the name of the js files used (I think the regex needs some review, I am not really good at regex...)
- hash the files to change the name

What is not done yet:
- copy the files to the temp directory and update the php file with the new name. The problem is that this is executed before Yeoman runs the basic build task, so the temp directory is not created yet. 
- repeat for the css files.

And if everything goes well, the default Yeoman build task is processed so all the rest will be done, such as image optimisation.

**Comment by romainberger** [comment] 2013-06-14 11:49
I am closing these issues as I haven't made any progress on the build task and don't plan to make any.
I personnally avoid as much as possible working with Wordpress right now and don't use this generator very often,
so I don't have a need for this.

I still keep the `build` branch if anyone is interested and I will continue to update and fix the issues in the generator if there are some.

**Closed as completed by romainberger** 2013-06-14 11:49 UTC
Labels: wontfix
